version: '3.4'

services:
  expressendpoint:
    image: expressendpoint
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5606:5606
